### ISSUE TITLE
dataInit script is dependent on non-working plugin

### ISSUE THREAD

**Issue by jamesmelville** [Vchalem/Health-Cloud---ADK#11]
The sfdx plugin `sfdx-wry-plugin` referred to in the `dataInit.sh` script and the partner setup instructions at https://salesforce.quip.com/SIUFAbtpCLDZ/Health-Cloud-Environments-for-Partners-External does not seem to work. It appears to install successfully, but on running the command `wry:file:replace` it errors:

```
user@pc:~$ sfdx wry:file:replace -i data/preprocess
 ›   Warning: wry:file:replace is not a sfdx command.
Did you mean plugins:update? [y/n]: n
 ›   Error: Run sfdx help for a list of available commands.
```
The error is already logged, along with a proposed fix at https://github.com/billryoung/sfdx-wry-plugin/issues/3

**Comment by tirtha83** [comment]
Got the same issue while running wry:file:replace command -
sfdx wry:file:replace -i data/preprocess       
 »   Warning: wry:file:replace is not a sfdx command.
Did you mean plugins:update? [y/n]:
 »   Error: Run sfdx help for a list of available commands.

**Comment by jrattanpal** [comment]
It is a plugin that you need to install to run data scripts.

https://www.npmjs.com/package/sfdx-wry-plugin
